### ISSUE TITLE
Error: EACCES: permission denied, mkdir 'log'

### ISSUE THREAD

**Issue by martinhalford** [accordproject/cicero-vscode-extension#12]
**Describe the bug**
After installing VSCode Extension receive following error, which is attempted five (5) times before VSCode gives up and stops trying to "restart the server".

Error: EACCES: permission denied, mkdir 'log'
    at Object.mkdirSync (fs.js:731:3)
    at setupLogger (/Users/martin/.vscode/extensions/accordproject.cicero-vscode-extension-0.13.0/server/node_modules/@accordproject/ergo-compiler/lib/logger.js:113:16)
    at Object.<anonymous> (/Users/martin/.vscode/extensions/accordproject.cicero-vscode-extension-0.13.0/server/node_modules/@accordproject/ergo-compiler/lib/logger.js:125:1)
    at Object.<anonymous> (/Users/martin/.vscode/extensions/accordproject.cicero-vscode-extension-0.13.0/server/node_modules/@accordproject/ergo-compiler/lib/logger.js:131:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
[Error - 7:53:22 AM] Connection to server got closed. Server will not be restarted.

**To Reproduce**
Install Accord VS-Code Extension v0.13.0 onto clean (i.e. never previously installed) VS-Code

**Expected behaviour**
VSCode Extension still appears to function normally after error displayed. No obvious functional bugs or other errors.

**Screenshots**
<img width="839" alt="Visual_Studio_Code" src="https://user-images.githubusercontent.com/970336/64738953-18a51b00-d534-11e9-9239-e49c78beee2f.png">

**Desktop:**
-- current installed Accord libraries are: 
      cicero v0.13.4
      ergoc v0.9.4
-- OS: macOS Mojave v10.14.6
-- VS Code: August 2019 (version 1.38)

**Comment by adrijshikhar** [comment]
@martinhalford Do you have the permissions to make changes to file system? From what I can see that you are getting `permissions denied, mkdir 'log'`.

**Comment by dselman** [comment]
Going to close this here -- it is related to log creation in Concerto -- I will open an issue there.
